apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: shipping
data:
  CART_ENDPOINT: cart:8080
  DB_HOST: roboshop-dev.c0jqouioew0k.us-east-1.rds.amazonaws.com