apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: shipping
spec: 
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      tier: backend
      component: shipping
  template:
    metadata:
      name: shipping
      labels:
        project: roboshop
        tier: backend
        component: shipping
    spec:
      containers:
        - name: shipping
          image: "{{ .Values.deployment.imageName }}:{{ .Values.deployment.imageVersion }}"
          imagePullPolicy: Always # safe to pull everytime. There may images which are fixed and pushed with same build version
          resources:
            requests:
              cpu: {{ .Values.deployment.request.cpu }}
              memory: {{ .Values.deployment.request.memory }}
            limits:
              cpu: {{ .Values.deployment.limits.cpu }}
              memory:  {{ .Values.deployment.limits.memory }}
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 2
          envFrom:
          - configMapRef:
              name: shipping
