apiVersion: kubernetes.k8.io/v1
kind: StorageClass
metadata:
  name: roboshop-ebs
  labels:
    project: roboshop
    environment: dev
    purpose: poc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
