apiVersion: v1
kind: ConfigMap
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: cart
data:
  REDIS_HOST: redis
  CATALOGUE_HOST: catalogue
  CATALOGUE_PORT: "8080"