apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
spec:
  selector:
    # labels are used for selector
    project: roboshop
    tier: backend
    component: cart
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port
