deployment:
  changeCause: "initial deployment"
  imageVersion: "1.4.0"
  imageName: "happielearning/shipping"
  request:
    cpu: "100m"
    memory: "150Mi"
  limits:
    cpu: "200m"
    memory: "250Mi"
configMap:
  DB_HOST: "roboshop-dev.c0jqouioew0k.us-east-1.rds.amazonaws.com"