apiVersion: v1
kind: Service
metadata: 
  name: roboshop-headless
  namespace: roboshop
  labels: 
    - project: roboshop
      tier: db
      component: mongodb
spec:
  clusterIp: None
  selector:
    project: roboshop
    tier: db
    component: mongodb
  ports:
    - protocol: TCP
      port: 27017 # service port
      targetPort: 27017 # container port

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
  labels: 
    - project: roboshop
      tier: db
      component: mongodb
spec:
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: mongodb
  serviceName: "mongodb-headless"
  replicas: "1"
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: mongodb
    spec:
      containers:
        - name: mongodb
          image: happielearning/mongodb:1.0.0
          volumeMounts:
            - name: mongodb
              mountPath: /data/db
  # Volume Cliam
  volumeClaimTemplates:
    - metadata:
        name: mongodb
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "roboshop-ebs"
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata: 
  name: mongodb
  namespace: roboshop
  labels: 
    - project: roboshop
      tier: db
      component: mongodb
spec:
  clusterIp: None
  selector:
    project: roboshop
    tier: db
    component: mongodb
  ports:
    - protocol: TCP
      port: 27017 # service port
      targetPort: 27017 # container port

