apiVersion: v1
kind: Service
metadata: 
  name: mongo-headless
  namespace: roboshop
  labels: 
    project: roboshop
    tier: db
    component: mongo
spec:
  clusterIP: None
  selector:
    project: roboshop
    tier: db
    component: mongo
  ports:
    - protocol: TCP
      port: 27017 # service port
      targetPort: 27017 # container port

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  namespace: roboshop
  labels: 
    project: roboshop
    tier: db
    component: mongo
spec:
  selector:
    matchLabels:
      project: roboshop
      tier: db
      component: mongo
  serviceName: "mongo-headless"
  replicas: 1
  template:
    metadata:
      labels:
        project: roboshop
        tier: db
        component: mongo
    spec:
      containers:
        - name: mongo
          image: happielearning/mongo:1.0.0
          volumeMounts:
            - name: mongo
              mountPath: /data/db
  # Volume Cliam
  volumeClaimTemplates:
    - metadata:
        name: mongo
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "roboshop-ebs"
        resources:
          requests:
            storage: 1Gi

---
apiVersion: v1
kind: Service
metadata: 
  name: mongo
  namespace: roboshop
  labels: 
    project: roboshop
    tier: db
    component: mongo
spec:
  selector:
    project: roboshop
    tier: db
    component: mongo
  ports:
    - protocol: TCP
      port: 27017 # service port
      targetPort: 27017 # container port

