apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    project: roboshop
    tier: frontend
    component: app1
  ports:
  - protocol: TCP
    port: 80 # servie port
    targetPort: 80 # container port