apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    tier: backend
    component: user
data:
  MONGO: "true"
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongo:27017/users"