name: Roboshop Infra AWS - Create
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "AWS Infra using Terraform"
        required: true
        default: "dev"
        type: choice
        options:
          - "dev"
          - "uat"
          - "prod"
env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  TF_VERSION: 1.15.1

jobs:
  vpc:
    name: VPC
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./00-vpc/dev/
    steps:
      - name: "Code checkout"
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Terraform init
        run: terraform init --backend-config=backend-dev.hcl

      - name: terraform validate
        run: terraform validate

      - name: terraform plan
        run: terraform plan --var-file=dev.tfvars -out=tfplan

      - name: terraform apply 
        run: terraform apply tfplan --auto-approve
  
  sg:
    name: SG
    runs-on: ubuntu-latest
    needs: vpc
    defaults:
      run:
        working-directory: ./10-sg/dev/
    steps:
      - name: "Code checkout"
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Terraform init
        run: terraform init --backend-config=backend-dev.hcl

      - name: terraform validate
        run: terraform validate

      - name: terraform plan
        run: terraform plan --var-file=dev.tfvars -out=tfplan

      - name: terraform apply 
        run: terraform apply tfplan --auto-approve
  
  sg-rules:
    name: SG Rules
    runs-on: ubuntu-latest
    needs: sg
    defaults:
      run:
        working-directory: ./20-sg-rules/dev/
    steps:
      - name: "Code checkout"
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Terraform init
        run: terraform init --backend-config=backend-dev.hcl

      - name: terraform validate
        run: terraform validate

      - name: terraform plan
        run: terraform plan --var-file=dev.tfvars -out=tfplan

      - name: terraform apply 
        run: terraform apply tfplan --auto-approve
